// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/msg_packet.proto

package com.msgtouch.network.socket.packet;

public final class MsgPBPacket {
  private MsgPBPacket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.msgtouch.common.proto.AppPlatform}
   */
  public enum AppPlatform
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Android = 1;</code>
     */
    Android(1),
    /**
     * <code>Web = 2;</code>
     */
    Web(2),
    /**
     * <code>Ios = 3;</code>
     */
    Ios(3),
    ;

    /**
     * <code>Android = 1;</code>
     */
    public static final int Android_VALUE = 1;
    /**
     * <code>Web = 2;</code>
     */
    public static final int Web_VALUE = 2;
    /**
     * <code>Ios = 3;</code>
     */
    public static final int Ios_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AppPlatform valueOf(int value) {
      return forNumber(value);
    }

    public static AppPlatform forNumber(int value) {
      switch (value) {
        case 1: return Android;
        case 2: return Web;
        case 3: return Ios;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AppPlatform>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AppPlatform> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AppPlatform>() {
            public AppPlatform findValueByNumber(int number) {
              return AppPlatform.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.msgtouch.network.socket.packet.MsgPBPacket.getDescriptor().getEnumTypes().get(0);
    }

    private static final AppPlatform[] VALUES = values();

    public static AppPlatform valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AppPlatform(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.msgtouch.common.proto.AppPlatform)
  }

  /**
   * Protobuf enum {@code com.msgtouch.common.proto.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Request = 1;</code>
     */
    Request(1),
    /**
     * <code>Response = 2;</code>
     */
    Response(2),
    ;

    /**
     * <code>Request = 1;</code>
     */
    public static final int Request_VALUE = 1;
    /**
     * <code>Response = 2;</code>
     */
    public static final int Response_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    public static MsgType forNumber(int value) {
      switch (value) {
        case 1: return Request;
        case 2: return Response;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.msgtouch.network.socket.packet.MsgPBPacket.getDescriptor().getEnumTypes().get(1);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.msgtouch.common.proto.MsgType)
  }

  /**
   * Protobuf enum {@code com.msgtouch.common.proto.RetCode}
   */
  public enum RetCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TIMEOUT = 1000;</code>
     */
    TIMEOUT(1000),
    /**
     * <pre>
     *正常 response
     * </pre>
     *
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>EXCEPTION = -1;</code>
     */
    EXCEPTION(-1),
    /**
     * <code>PROTO_ERROR = -2;</code>
     */
    PROTO_ERROR(-2),
    /**
     * <pre>
     * 告诉客户端重新登录
     * </pre>
     *
     * <code>ERROR_NO_SESSION = -3;</code>
     */
    ERROR_NO_SESSION(-3),
    /**
     * <code>PUSH = -4;</code>
     */
    PUSH(-4),
    ;

    /**
     * <code>TIMEOUT = 1000;</code>
     */
    public static final int TIMEOUT_VALUE = 1000;
    /**
     * <pre>
     *正常 response
     * </pre>
     *
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>EXCEPTION = -1;</code>
     */
    public static final int EXCEPTION_VALUE = -1;
    /**
     * <code>PROTO_ERROR = -2;</code>
     */
    public static final int PROTO_ERROR_VALUE = -2;
    /**
     * <pre>
     * 告诉客户端重新登录
     * </pre>
     *
     * <code>ERROR_NO_SESSION = -3;</code>
     */
    public static final int ERROR_NO_SESSION_VALUE = -3;
    /**
     * <code>PUSH = -4;</code>
     */
    public static final int PUSH_VALUE = -4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RetCode valueOf(int value) {
      return forNumber(value);
    }

    public static RetCode forNumber(int value) {
      switch (value) {
        case 1000: return TIMEOUT;
        case 0: return OK;
        case -1: return EXCEPTION;
        case -2: return PROTO_ERROR;
        case -3: return ERROR_NO_SESSION;
        case -4: return PUSH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RetCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RetCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RetCode>() {
            public RetCode findValueByNumber(int number) {
              return RetCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.msgtouch.network.socket.packet.MsgPBPacket.getDescriptor().getEnumTypes().get(2);
    }

    private static final RetCode[] VALUES = values();

    public static RetCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RetCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.msgtouch.common.proto.RetCode)
  }

  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.msgtouch.common.proto.Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.msgtouch.common.proto.MsgType msgType = 1;</code>
     */
    boolean hasMsgType();
    /**
     * <code>optional .com.msgtouch.common.proto.MsgType msgType = 1;</code>
     */
    com.msgtouch.network.socket.packet.MsgPBPacket.MsgType getMsgType();

    /**
     * <code>optional string seq = 2;</code>
     */
    boolean hasSeq();
    /**
     * <code>optional string seq = 2;</code>
     */
    java.lang.String getSeq();
    /**
     * <code>optional string seq = 2;</code>
     */
    com.google.protobuf.ByteString
        getSeqBytes();

    /**
     * <pre>
     * app 名字
     * </pre>
     *
     * <code>optional string appName = 3;</code>
     */
    boolean hasAppName();
    /**
     * <pre>
     * app 名字
     * </pre>
     *
     * <code>optional string appName = 3;</code>
     */
    java.lang.String getAppName();
    /**
     * <pre>
     * app 名字
     * </pre>
     *
     * <code>optional string appName = 3;</code>
     */
    com.google.protobuf.ByteString
        getAppNameBytes();

    /**
     * <pre>
     * 客户端类型
     * </pre>
     *
     * <code>optional .com.msgtouch.common.proto.AppPlatform platform = 4;</code>
     */
    boolean hasPlatform();
    /**
     * <pre>
     * 客户端类型
     * </pre>
     *
     * <code>optional .com.msgtouch.common.proto.AppPlatform platform = 4;</code>
     */
    com.msgtouch.network.socket.packet.MsgPBPacket.AppPlatform getPlatform();

    /**
     * <pre>
     * main cmds
     * </pre>
     *
     * <code>optional string cmd = 5;</code>
     */
    boolean hasCmd();
    /**
     * <pre>
     * main cmds
     * </pre>
     *
     * <code>optional string cmd = 5;</code>
     */
    java.lang.String getCmd();
    /**
     * <pre>
     * main cmds
     * </pre>
     *
     * <code>optional string cmd = 5;</code>
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <code>optional string customerId = 6;</code>
     */
    boolean hasCustomerId();
    /**
     * <code>optional string customerId = 6;</code>
     */
    java.lang.String getCustomerId();
    /**
     * <code>optional string customerId = 6;</code>
     */
    com.google.protobuf.ByteString
        getCustomerIdBytes();

    /**
     * <pre>
     *user identity(sessionID)
     * </pre>
     *
     * <code>optional uint64 uid = 7;</code>
     */
    boolean hasUid();
    /**
     * <pre>
     *user identity(sessionID)
     * </pre>
     *
     * <code>optional uint64 uid = 7;</code>
     */
    long getUid();

    /**
     * <pre>
     * error
     * </pre>
     *
     * <code>optional string error = 8;</code>
     */
    boolean hasError();
    /**
     * <pre>
     * error
     * </pre>
     *
     * <code>optional string error = 8;</code>
     */
    java.lang.String getError();
    /**
     * <pre>
     * error
     * </pre>
     *
     * <code>optional string error = 8;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();

    /**
     * <pre>
     * encrypt body
     * </pre>
     *
     * <code>optional bytes eBody = 9;</code>
     */
    boolean hasEBody();
    /**
     * <pre>
     * encrypt body
     * </pre>
     *
     * <code>optional bytes eBody = 9;</code>
     */
    com.google.protobuf.ByteString getEBody();

    /**
     * <pre>
     *游戏id
     * </pre>
     *
     * <code>optional string gameId = 10;</code>
     */
    boolean hasGameId();
    /**
     * <pre>
     *游戏id
     * </pre>
     *
     * <code>optional string gameId = 10;</code>
     */
    java.lang.String getGameId();
    /**
     * <pre>
     *游戏id
     * </pre>
     *
     * <code>optional string gameId = 10;</code>
     */
    com.google.protobuf.ByteString
        getGameIdBytes();

    /**
     * <pre>
     *渠道号
     * </pre>
     *
     * <code>optional string advno = 11;</code>
     */
    boolean hasAdvno();
    /**
     * <pre>
     *渠道号
     * </pre>
     *
     * <code>optional string advno = 11;</code>
     */
    java.lang.String getAdvno();
    /**
     * <pre>
     *渠道号
     * </pre>
     *
     * <code>optional string advno = 11;</code>
     */
    com.google.protobuf.ByteString
        getAdvnoBytes();

    /**
     * <pre>
     * sdk 版本
     * </pre>
     *
     * <code>optional string sdkVersion = 12;</code>
     */
    boolean hasSdkVersion();
    /**
     * <pre>
     * sdk 版本
     * </pre>
     *
     * <code>optional string sdkVersion = 12;</code>
     */
    java.lang.String getSdkVersion();
    /**
     * <pre>
     * sdk 版本
     * </pre>
     *
     * <code>optional string sdkVersion = 12;</code>
     */
    com.google.protobuf.ByteString
        getSdkVersionBytes();

    /**
     * <pre>
     * imei
     * </pre>
     *
     * <code>optional string imei = 13;</code>
     */
    boolean hasImei();
    /**
     * <pre>
     * imei
     * </pre>
     *
     * <code>optional string imei = 13;</code>
     */
    java.lang.String getImei();
    /**
     * <pre>
     * imei
     * </pre>
     *
     * <code>optional string imei = 13;</code>
     */
    com.google.protobuf.ByteString
        getImeiBytes();

    /**
     * <code>optional .com.msgtouch.common.proto.RetCode retCode = 14;</code>
     */
    boolean hasRetCode();
    /**
     * <code>optional .com.msgtouch.common.proto.RetCode retCode = 14;</code>
     */
    com.msgtouch.network.socket.packet.MsgPBPacket.RetCode getRetCode();
  }
  /**
   * Protobuf type {@code com.msgtouch.common.proto.Packet}
   */
  public  static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.msgtouch.common.proto.Packet)
      PacketOrBuilder {
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      msgType_ = 1;
      seq_ = "";
      appName_ = "";
      platform_ = 1;
      cmd_ = "";
      customerId_ = "";
      uid_ = 0L;
      error_ = "";
      eBody_ = com.google.protobuf.ByteString.EMPTY;
      gameId_ = "";
      advno_ = "";
      sdkVersion_ = "";
      imei_ = "";
      retCode_ = 1000;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.msgtouch.network.socket.packet.MsgPBPacket.MsgType value = com.msgtouch.network.socket.packet.MsgPBPacket.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgType_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              seq_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              appName_ = bs;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.msgtouch.network.socket.packet.MsgPBPacket.AppPlatform value = com.msgtouch.network.socket.packet.MsgPBPacket.AppPlatform.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                platform_ = rawValue;
              }
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              cmd_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              customerId_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              uid_ = input.readUInt64();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              error_ = bs;
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              eBody_ = input.readBytes();
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              gameId_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              advno_ = bs;
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000800;
              sdkVersion_ = bs;
              break;
            }
            case 106: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00001000;
              imei_ = bs;
              break;
            }
            case 112: {
              int rawValue = input.readEnum();
              com.msgtouch.network.socket.packet.MsgPBPacket.RetCode value = com.msgtouch.network.socket.packet.MsgPBPacket.RetCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(14, rawValue);
              } else {
                bitField0_ |= 0x00002000;
                retCode_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.msgtouch.network.socket.packet.MsgPBPacket.internal_static_com_msgtouch_common_proto_Packet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.msgtouch.network.socket.packet.MsgPBPacket.internal_static_com_msgtouch_common_proto_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.msgtouch.network.socket.packet.MsgPBPacket.Packet.class, com.msgtouch.network.socket.packet.MsgPBPacket.Packet.Builder.class);
    }

    private int bitField0_;
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <code>optional .com.msgtouch.common.proto.MsgType msgType = 1;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.msgtouch.common.proto.MsgType msgType = 1;</code>
     */
    public com.msgtouch.network.socket.packet.MsgPBPacket.MsgType getMsgType() {
      com.msgtouch.network.socket.packet.MsgPBPacket.MsgType result = com.msgtouch.network.socket.packet.MsgPBPacket.MsgType.valueOf(msgType_);
      return result == null ? com.msgtouch.network.socket.packet.MsgPBPacket.MsgType.Request : result;
    }

    public static final int SEQ_FIELD_NUMBER = 2;
    private volatile java.lang.Object seq_;
    /**
     * <code>optional string seq = 2;</code>
     */
    public boolean hasSeq() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string seq = 2;</code>
     */
    public java.lang.String getSeq() {
      java.lang.Object ref = seq_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          seq_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string seq = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSeqBytes() {
      java.lang.Object ref = seq_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        seq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object appName_;
    /**
     * <pre>
     * app 名字
     * </pre>
     *
     * <code>optional string appName = 3;</code>
     */
    public boolean hasAppName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * app 名字
     * </pre>
     *
     * <code>optional string appName = 3;</code>
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appName_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * app 名字
     * </pre>
     *
     * <code>optional string appName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLATFORM_FIELD_NUMBER = 4;
    private int platform_;
    /**
     * <pre>
     * 客户端类型
     * </pre>
     *
     * <code>optional .com.msgtouch.common.proto.AppPlatform platform = 4;</code>
     */
    public boolean hasPlatform() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * 客户端类型
     * </pre>
     *
     * <code>optional .com.msgtouch.common.proto.AppPlatform platform = 4;</code>
     */
    public com.msgtouch.network.socket.packet.MsgPBPacket.AppPlatform getPlatform() {
      com.msgtouch.network.socket.packet.MsgPBPacket.AppPlatform result = com.msgtouch.network.socket.packet.MsgPBPacket.AppPlatform.valueOf(platform_);
      return result == null ? com.msgtouch.network.socket.packet.MsgPBPacket.AppPlatform.Android : result;
    }

    public static final int CMD_FIELD_NUMBER = 5;
    private volatile java.lang.Object cmd_;
    /**
     * <pre>
     * main cmds
     * </pre>
     *
     * <code>optional string cmd = 5;</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * main cmds
     * </pre>
     *
     * <code>optional string cmd = 5;</code>
     */
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cmd_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * main cmds
     * </pre>
     *
     * <code>optional string cmd = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMERID_FIELD_NUMBER = 6;
    private volatile java.lang.Object customerId_;
    /**
     * <code>optional string customerId = 6;</code>
     */
    public boolean hasCustomerId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string customerId = 6;</code>
     */
    public java.lang.String getCustomerId() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          customerId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string customerId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCustomerIdBytes() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UID_FIELD_NUMBER = 7;
    private long uid_;
    /**
     * <pre>
     *user identity(sessionID)
     * </pre>
     *
     * <code>optional uint64 uid = 7;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     *user identity(sessionID)
     * </pre>
     *
     * <code>optional uint64 uid = 7;</code>
     */
    public long getUid() {
      return uid_;
    }

    public static final int ERROR_FIELD_NUMBER = 8;
    private volatile java.lang.Object error_;
    /**
     * <pre>
     * error
     * </pre>
     *
     * <code>optional string error = 8;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     * error
     * </pre>
     *
     * <code>optional string error = 8;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          error_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * error
     * </pre>
     *
     * <code>optional string error = 8;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EBODY_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString eBody_;
    /**
     * <pre>
     * encrypt body
     * </pre>
     *
     * <code>optional bytes eBody = 9;</code>
     */
    public boolean hasEBody() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <pre>
     * encrypt body
     * </pre>
     *
     * <code>optional bytes eBody = 9;</code>
     */
    public com.google.protobuf.ByteString getEBody() {
      return eBody_;
    }

    public static final int GAMEID_FIELD_NUMBER = 10;
    private volatile java.lang.Object gameId_;
    /**
     * <pre>
     *游戏id
     * </pre>
     *
     * <code>optional string gameId = 10;</code>
     */
    public boolean hasGameId() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <pre>
     *游戏id
     * </pre>
     *
     * <code>optional string gameId = 10;</code>
     */
    public java.lang.String getGameId() {
      java.lang.Object ref = gameId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gameId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *游戏id
     * </pre>
     *
     * <code>optional string gameId = 10;</code>
     */
    public com.google.protobuf.ByteString
        getGameIdBytes() {
      java.lang.Object ref = gameId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADVNO_FIELD_NUMBER = 11;
    private volatile java.lang.Object advno_;
    /**
     * <pre>
     *渠道号
     * </pre>
     *
     * <code>optional string advno = 11;</code>
     */
    public boolean hasAdvno() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <pre>
     *渠道号
     * </pre>
     *
     * <code>optional string advno = 11;</code>
     */
    public java.lang.String getAdvno() {
      java.lang.Object ref = advno_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          advno_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *渠道号
     * </pre>
     *
     * <code>optional string advno = 11;</code>
     */
    public com.google.protobuf.ByteString
        getAdvnoBytes() {
      java.lang.Object ref = advno_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        advno_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SDKVERSION_FIELD_NUMBER = 12;
    private volatile java.lang.Object sdkVersion_;
    /**
     * <pre>
     * sdk 版本
     * </pre>
     *
     * <code>optional string sdkVersion = 12;</code>
     */
    public boolean hasSdkVersion() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <pre>
     * sdk 版本
     * </pre>
     *
     * <code>optional string sdkVersion = 12;</code>
     */
    public java.lang.String getSdkVersion() {
      java.lang.Object ref = sdkVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sdkVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * sdk 版本
     * </pre>
     *
     * <code>optional string sdkVersion = 12;</code>
     */
    public com.google.protobuf.ByteString
        getSdkVersionBytes() {
      java.lang.Object ref = sdkVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sdkVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMEI_FIELD_NUMBER = 13;
    private volatile java.lang.Object imei_;
    /**
     * <pre>
     * imei
     * </pre>
     *
     * <code>optional string imei = 13;</code>
     */
    public boolean hasImei() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <pre>
     * imei
     * </pre>
     *
     * <code>optional string imei = 13;</code>
     */
    public java.lang.String getImei() {
      java.lang.Object ref = imei_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imei_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * imei
     * </pre>
     *
     * <code>optional string imei = 13;</code>
     */
    public com.google.protobuf.ByteString
        getImeiBytes() {
      java.lang.Object ref = imei_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RETCODE_FIELD_NUMBER = 14;
    private int retCode_;
    /**
     * <code>optional .com.msgtouch.common.proto.RetCode retCode = 14;</code>
     */
    public boolean hasRetCode() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional .com.msgtouch.common.proto.RetCode retCode = 14;</code>
     */
    public com.msgtouch.network.socket.packet.MsgPBPacket.RetCode getRetCode() {
      com.msgtouch.network.socket.packet.MsgPBPacket.RetCode result = com.msgtouch.network.socket.packet.MsgPBPacket.RetCode.valueOf(retCode_);
      return result == null ? com.msgtouch.network.socket.packet.MsgPBPacket.RetCode.TIMEOUT : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, seq_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, platform_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cmd_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, customerId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(7, uid_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, error_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, eBody_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, gameId_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, advno_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, sdkVersion_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, imei_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeEnum(14, retCode_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, seq_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, platform_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, cmd_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, customerId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, uid_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, error_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, eBody_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, gameId_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, advno_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, sdkVersion_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, imei_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(14, retCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.msgtouch.network.socket.packet.MsgPBPacket.Packet)) {
        return super.equals(obj);
      }
      com.msgtouch.network.socket.packet.MsgPBPacket.Packet other = (com.msgtouch.network.socket.packet.MsgPBPacket.Packet) obj;

      boolean result = true;
      result = result && (hasMsgType() == other.hasMsgType());
      if (hasMsgType()) {
        result = result && msgType_ == other.msgType_;
      }
      result = result && (hasSeq() == other.hasSeq());
      if (hasSeq()) {
        result = result && getSeq()
            .equals(other.getSeq());
      }
      result = result && (hasAppName() == other.hasAppName());
      if (hasAppName()) {
        result = result && getAppName()
            .equals(other.getAppName());
      }
      result = result && (hasPlatform() == other.hasPlatform());
      if (hasPlatform()) {
        result = result && platform_ == other.platform_;
      }
      result = result && (hasCmd() == other.hasCmd());
      if (hasCmd()) {
        result = result && getCmd()
            .equals(other.getCmd());
      }
      result = result && (hasCustomerId() == other.hasCustomerId());
      if (hasCustomerId()) {
        result = result && getCustomerId()
            .equals(other.getCustomerId());
      }
      result = result && (hasUid() == other.hasUid());
      if (hasUid()) {
        result = result && (getUid()
            == other.getUid());
      }
      result = result && (hasError() == other.hasError());
      if (hasError()) {
        result = result && getError()
            .equals(other.getError());
      }
      result = result && (hasEBody() == other.hasEBody());
      if (hasEBody()) {
        result = result && getEBody()
            .equals(other.getEBody());
      }
      result = result && (hasGameId() == other.hasGameId());
      if (hasGameId()) {
        result = result && getGameId()
            .equals(other.getGameId());
      }
      result = result && (hasAdvno() == other.hasAdvno());
      if (hasAdvno()) {
        result = result && getAdvno()
            .equals(other.getAdvno());
      }
      result = result && (hasSdkVersion() == other.hasSdkVersion());
      if (hasSdkVersion()) {
        result = result && getSdkVersion()
            .equals(other.getSdkVersion());
      }
      result = result && (hasImei() == other.hasImei());
      if (hasImei()) {
        result = result && getImei()
            .equals(other.getImei());
      }
      result = result && (hasRetCode() == other.hasRetCode());
      if (hasRetCode()) {
        result = result && retCode_ == other.retCode_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMsgType()) {
        hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + msgType_;
      }
      if (hasSeq()) {
        hash = (37 * hash) + SEQ_FIELD_NUMBER;
        hash = (53 * hash) + getSeq().hashCode();
      }
      if (hasAppName()) {
        hash = (37 * hash) + APPNAME_FIELD_NUMBER;
        hash = (53 * hash) + getAppName().hashCode();
      }
      if (hasPlatform()) {
        hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
        hash = (53 * hash) + platform_;
      }
      if (hasCmd()) {
        hash = (37 * hash) + CMD_FIELD_NUMBER;
        hash = (53 * hash) + getCmd().hashCode();
      }
      if (hasCustomerId()) {
        hash = (37 * hash) + CUSTOMERID_FIELD_NUMBER;
        hash = (53 * hash) + getCustomerId().hashCode();
      }
      if (hasUid()) {
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUid());
      }
      if (hasError()) {
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
      }
      if (hasEBody()) {
        hash = (37 * hash) + EBODY_FIELD_NUMBER;
        hash = (53 * hash) + getEBody().hashCode();
      }
      if (hasGameId()) {
        hash = (37 * hash) + GAMEID_FIELD_NUMBER;
        hash = (53 * hash) + getGameId().hashCode();
      }
      if (hasAdvno()) {
        hash = (37 * hash) + ADVNO_FIELD_NUMBER;
        hash = (53 * hash) + getAdvno().hashCode();
      }
      if (hasSdkVersion()) {
        hash = (37 * hash) + SDKVERSION_FIELD_NUMBER;
        hash = (53 * hash) + getSdkVersion().hashCode();
      }
      if (hasImei()) {
        hash = (37 * hash) + IMEI_FIELD_NUMBER;
        hash = (53 * hash) + getImei().hashCode();
      }
      if (hasRetCode()) {
        hash = (37 * hash) + RETCODE_FIELD_NUMBER;
        hash = (53 * hash) + retCode_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.msgtouch.network.socket.packet.MsgPBPacket.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.msgtouch.network.socket.packet.MsgPBPacket.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.msgtouch.network.socket.packet.MsgPBPacket.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.msgtouch.network.socket.packet.MsgPBPacket.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.msgtouch.network.socket.packet.MsgPBPacket.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.msgtouch.network.socket.packet.MsgPBPacket.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.msgtouch.network.socket.packet.MsgPBPacket.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.msgtouch.network.socket.packet.MsgPBPacket.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.msgtouch.network.socket.packet.MsgPBPacket.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.msgtouch.network.socket.packet.MsgPBPacket.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.msgtouch.network.socket.packet.MsgPBPacket.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.msgtouch.common.proto.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.msgtouch.common.proto.Packet)
        com.msgtouch.network.socket.packet.MsgPBPacket.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.msgtouch.network.socket.packet.MsgPBPacket.internal_static_com_msgtouch_common_proto_Packet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.msgtouch.network.socket.packet.MsgPBPacket.internal_static_com_msgtouch_common_proto_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.msgtouch.network.socket.packet.MsgPBPacket.Packet.class, com.msgtouch.network.socket.packet.MsgPBPacket.Packet.Builder.class);
      }

      // Construct using com.msgtouch.network.socket.packet.MsgPBPacket.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        seq_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        appName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        platform_ = 1;
        bitField0_ = (bitField0_ & ~0x00000008);
        cmd_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        customerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        eBody_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        gameId_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        advno_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        sdkVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        imei_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        retCode_ = 1000;
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.msgtouch.network.socket.packet.MsgPBPacket.internal_static_com_msgtouch_common_proto_Packet_descriptor;
      }

      public com.msgtouch.network.socket.packet.MsgPBPacket.Packet getDefaultInstanceForType() {
        return com.msgtouch.network.socket.packet.MsgPBPacket.Packet.getDefaultInstance();
      }

      public com.msgtouch.network.socket.packet.MsgPBPacket.Packet build() {
        com.msgtouch.network.socket.packet.MsgPBPacket.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.msgtouch.network.socket.packet.MsgPBPacket.Packet buildPartial() {
        com.msgtouch.network.socket.packet.MsgPBPacket.Packet result = new com.msgtouch.network.socket.packet.MsgPBPacket.Packet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.seq_ = seq_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.appName_ = appName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.platform_ = platform_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.customerId_ = customerId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.error_ = error_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.eBody_ = eBody_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.gameId_ = gameId_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.advno_ = advno_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.sdkVersion_ = sdkVersion_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.imei_ = imei_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.retCode_ = retCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.msgtouch.network.socket.packet.MsgPBPacket.Packet) {
          return mergeFrom((com.msgtouch.network.socket.packet.MsgPBPacket.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.msgtouch.network.socket.packet.MsgPBPacket.Packet other) {
        if (other == com.msgtouch.network.socket.packet.MsgPBPacket.Packet.getDefaultInstance()) return this;
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasSeq()) {
          bitField0_ |= 0x00000002;
          seq_ = other.seq_;
          onChanged();
        }
        if (other.hasAppName()) {
          bitField0_ |= 0x00000004;
          appName_ = other.appName_;
          onChanged();
        }
        if (other.hasPlatform()) {
          setPlatform(other.getPlatform());
        }
        if (other.hasCmd()) {
          bitField0_ |= 0x00000010;
          cmd_ = other.cmd_;
          onChanged();
        }
        if (other.hasCustomerId()) {
          bitField0_ |= 0x00000020;
          customerId_ = other.customerId_;
          onChanged();
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasError()) {
          bitField0_ |= 0x00000080;
          error_ = other.error_;
          onChanged();
        }
        if (other.hasEBody()) {
          setEBody(other.getEBody());
        }
        if (other.hasGameId()) {
          bitField0_ |= 0x00000200;
          gameId_ = other.gameId_;
          onChanged();
        }
        if (other.hasAdvno()) {
          bitField0_ |= 0x00000400;
          advno_ = other.advno_;
          onChanged();
        }
        if (other.hasSdkVersion()) {
          bitField0_ |= 0x00000800;
          sdkVersion_ = other.sdkVersion_;
          onChanged();
        }
        if (other.hasImei()) {
          bitField0_ |= 0x00001000;
          imei_ = other.imei_;
          onChanged();
        }
        if (other.hasRetCode()) {
          setRetCode(other.getRetCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.msgtouch.network.socket.packet.MsgPBPacket.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.msgtouch.network.socket.packet.MsgPBPacket.Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgType_ = 1;
      /**
       * <code>optional .com.msgtouch.common.proto.MsgType msgType = 1;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.msgtouch.common.proto.MsgType msgType = 1;</code>
       */
      public com.msgtouch.network.socket.packet.MsgPBPacket.MsgType getMsgType() {
        com.msgtouch.network.socket.packet.MsgPBPacket.MsgType result = com.msgtouch.network.socket.packet.MsgPBPacket.MsgType.valueOf(msgType_);
        return result == null ? com.msgtouch.network.socket.packet.MsgPBPacket.MsgType.Request : result;
      }
      /**
       * <code>optional .com.msgtouch.common.proto.MsgType msgType = 1;</code>
       */
      public Builder setMsgType(com.msgtouch.network.socket.packet.MsgPBPacket.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.msgtouch.common.proto.MsgType msgType = 1;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object seq_ = "";
      /**
       * <code>optional string seq = 2;</code>
       */
      public boolean hasSeq() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string seq = 2;</code>
       */
      public java.lang.String getSeq() {
        java.lang.Object ref = seq_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            seq_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string seq = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSeqBytes() {
        java.lang.Object ref = seq_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          seq_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string seq = 2;</code>
       */
      public Builder setSeq(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string seq = 2;</code>
       */
      public Builder clearSeq() {
        bitField0_ = (bitField0_ & ~0x00000002);
        seq_ = getDefaultInstance().getSeq();
        onChanged();
        return this;
      }
      /**
       * <code>optional string seq = 2;</code>
       */
      public Builder setSeqBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        seq_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appName_ = "";
      /**
       * <pre>
       * app 名字
       * </pre>
       *
       * <code>optional string appName = 3;</code>
       */
      public boolean hasAppName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * app 名字
       * </pre>
       *
       * <code>optional string appName = 3;</code>
       */
      public java.lang.String getAppName() {
        java.lang.Object ref = appName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * app 名字
       * </pre>
       *
       * <code>optional string appName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAppNameBytes() {
        java.lang.Object ref = appName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * app 名字
       * </pre>
       *
       * <code>optional string appName = 3;</code>
       */
      public Builder setAppName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        appName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * app 名字
       * </pre>
       *
       * <code>optional string appName = 3;</code>
       */
      public Builder clearAppName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        appName_ = getDefaultInstance().getAppName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * app 名字
       * </pre>
       *
       * <code>optional string appName = 3;</code>
       */
      public Builder setAppNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        appName_ = value;
        onChanged();
        return this;
      }

      private int platform_ = 1;
      /**
       * <pre>
       * 客户端类型
       * </pre>
       *
       * <code>optional .com.msgtouch.common.proto.AppPlatform platform = 4;</code>
       */
      public boolean hasPlatform() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * 客户端类型
       * </pre>
       *
       * <code>optional .com.msgtouch.common.proto.AppPlatform platform = 4;</code>
       */
      public com.msgtouch.network.socket.packet.MsgPBPacket.AppPlatform getPlatform() {
        com.msgtouch.network.socket.packet.MsgPBPacket.AppPlatform result = com.msgtouch.network.socket.packet.MsgPBPacket.AppPlatform.valueOf(platform_);
        return result == null ? com.msgtouch.network.socket.packet.MsgPBPacket.AppPlatform.Android : result;
      }
      /**
       * <pre>
       * 客户端类型
       * </pre>
       *
       * <code>optional .com.msgtouch.common.proto.AppPlatform platform = 4;</code>
       */
      public Builder setPlatform(com.msgtouch.network.socket.packet.MsgPBPacket.AppPlatform value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        platform_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端类型
       * </pre>
       *
       * <code>optional .com.msgtouch.common.proto.AppPlatform platform = 4;</code>
       */
      public Builder clearPlatform() {
        bitField0_ = (bitField0_ & ~0x00000008);
        platform_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <pre>
       * main cmds
       * </pre>
       *
       * <code>optional string cmd = 5;</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * main cmds
       * </pre>
       *
       * <code>optional string cmd = 5;</code>
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cmd_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * main cmds
       * </pre>
       *
       * <code>optional string cmd = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * main cmds
       * </pre>
       *
       * <code>optional string cmd = 5;</code>
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * main cmds
       * </pre>
       *
       * <code>optional string cmd = 5;</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000010);
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * main cmds
       * </pre>
       *
       * <code>optional string cmd = 5;</code>
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        cmd_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object customerId_ = "";
      /**
       * <code>optional string customerId = 6;</code>
       */
      public boolean hasCustomerId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string customerId = 6;</code>
       */
      public java.lang.String getCustomerId() {
        java.lang.Object ref = customerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            customerId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string customerId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCustomerIdBytes() {
        java.lang.Object ref = customerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string customerId = 6;</code>
       */
      public Builder setCustomerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        customerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string customerId = 6;</code>
       */
      public Builder clearCustomerId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        customerId_ = getDefaultInstance().getCustomerId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string customerId = 6;</code>
       */
      public Builder setCustomerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        customerId_ = value;
        onChanged();
        return this;
      }

      private long uid_ ;
      /**
       * <pre>
       *user identity(sessionID)
       * </pre>
       *
       * <code>optional uint64 uid = 7;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       *user identity(sessionID)
       * </pre>
       *
       * <code>optional uint64 uid = 7;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <pre>
       *user identity(sessionID)
       * </pre>
       *
       * <code>optional uint64 uid = 7;</code>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000040;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *user identity(sessionID)
       * </pre>
       *
       * <code>optional uint64 uid = 7;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000040);
        uid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object error_ = "";
      /**
       * <pre>
       * error
       * </pre>
       *
       * <code>optional string error = 8;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       * error
       * </pre>
       *
       * <code>optional string error = 8;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            error_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * error
       * </pre>
       *
       * <code>optional string error = 8;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * error
       * </pre>
       *
       * <code>optional string error = 8;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * error
       * </pre>
       *
       * <code>optional string error = 8;</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000080);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * error
       * </pre>
       *
       * <code>optional string error = 8;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        error_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString eBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * encrypt body
       * </pre>
       *
       * <code>optional bytes eBody = 9;</code>
       */
      public boolean hasEBody() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <pre>
       * encrypt body
       * </pre>
       *
       * <code>optional bytes eBody = 9;</code>
       */
      public com.google.protobuf.ByteString getEBody() {
        return eBody_;
      }
      /**
       * <pre>
       * encrypt body
       * </pre>
       *
       * <code>optional bytes eBody = 9;</code>
       */
      public Builder setEBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        eBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * encrypt body
       * </pre>
       *
       * <code>optional bytes eBody = 9;</code>
       */
      public Builder clearEBody() {
        bitField0_ = (bitField0_ & ~0x00000100);
        eBody_ = getDefaultInstance().getEBody();
        onChanged();
        return this;
      }

      private java.lang.Object gameId_ = "";
      /**
       * <pre>
       *游戏id
       * </pre>
       *
       * <code>optional string gameId = 10;</code>
       */
      public boolean hasGameId() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <pre>
       *游戏id
       * </pre>
       *
       * <code>optional string gameId = 10;</code>
       */
      public java.lang.String getGameId() {
        java.lang.Object ref = gameId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            gameId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *游戏id
       * </pre>
       *
       * <code>optional string gameId = 10;</code>
       */
      public com.google.protobuf.ByteString
          getGameIdBytes() {
        java.lang.Object ref = gameId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gameId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *游戏id
       * </pre>
       *
       * <code>optional string gameId = 10;</code>
       */
      public Builder setGameId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        gameId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *游戏id
       * </pre>
       *
       * <code>optional string gameId = 10;</code>
       */
      public Builder clearGameId() {
        bitField0_ = (bitField0_ & ~0x00000200);
        gameId_ = getDefaultInstance().getGameId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *游戏id
       * </pre>
       *
       * <code>optional string gameId = 10;</code>
       */
      public Builder setGameIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        gameId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object advno_ = "";
      /**
       * <pre>
       *渠道号
       * </pre>
       *
       * <code>optional string advno = 11;</code>
       */
      public boolean hasAdvno() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <pre>
       *渠道号
       * </pre>
       *
       * <code>optional string advno = 11;</code>
       */
      public java.lang.String getAdvno() {
        java.lang.Object ref = advno_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            advno_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *渠道号
       * </pre>
       *
       * <code>optional string advno = 11;</code>
       */
      public com.google.protobuf.ByteString
          getAdvnoBytes() {
        java.lang.Object ref = advno_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          advno_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *渠道号
       * </pre>
       *
       * <code>optional string advno = 11;</code>
       */
      public Builder setAdvno(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        advno_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *渠道号
       * </pre>
       *
       * <code>optional string advno = 11;</code>
       */
      public Builder clearAdvno() {
        bitField0_ = (bitField0_ & ~0x00000400);
        advno_ = getDefaultInstance().getAdvno();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *渠道号
       * </pre>
       *
       * <code>optional string advno = 11;</code>
       */
      public Builder setAdvnoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        advno_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sdkVersion_ = "";
      /**
       * <pre>
       * sdk 版本
       * </pre>
       *
       * <code>optional string sdkVersion = 12;</code>
       */
      public boolean hasSdkVersion() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <pre>
       * sdk 版本
       * </pre>
       *
       * <code>optional string sdkVersion = 12;</code>
       */
      public java.lang.String getSdkVersion() {
        java.lang.Object ref = sdkVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sdkVersion_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * sdk 版本
       * </pre>
       *
       * <code>optional string sdkVersion = 12;</code>
       */
      public com.google.protobuf.ByteString
          getSdkVersionBytes() {
        java.lang.Object ref = sdkVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sdkVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * sdk 版本
       * </pre>
       *
       * <code>optional string sdkVersion = 12;</code>
       */
      public Builder setSdkVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        sdkVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * sdk 版本
       * </pre>
       *
       * <code>optional string sdkVersion = 12;</code>
       */
      public Builder clearSdkVersion() {
        bitField0_ = (bitField0_ & ~0x00000800);
        sdkVersion_ = getDefaultInstance().getSdkVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * sdk 版本
       * </pre>
       *
       * <code>optional string sdkVersion = 12;</code>
       */
      public Builder setSdkVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        sdkVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object imei_ = "";
      /**
       * <pre>
       * imei
       * </pre>
       *
       * <code>optional string imei = 13;</code>
       */
      public boolean hasImei() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <pre>
       * imei
       * </pre>
       *
       * <code>optional string imei = 13;</code>
       */
      public java.lang.String getImei() {
        java.lang.Object ref = imei_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            imei_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * imei
       * </pre>
       *
       * <code>optional string imei = 13;</code>
       */
      public com.google.protobuf.ByteString
          getImeiBytes() {
        java.lang.Object ref = imei_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imei_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * imei
       * </pre>
       *
       * <code>optional string imei = 13;</code>
       */
      public Builder setImei(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        imei_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * imei
       * </pre>
       *
       * <code>optional string imei = 13;</code>
       */
      public Builder clearImei() {
        bitField0_ = (bitField0_ & ~0x00001000);
        imei_ = getDefaultInstance().getImei();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * imei
       * </pre>
       *
       * <code>optional string imei = 13;</code>
       */
      public Builder setImeiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        imei_ = value;
        onChanged();
        return this;
      }

      private int retCode_ = 1000;
      /**
       * <code>optional .com.msgtouch.common.proto.RetCode retCode = 14;</code>
       */
      public boolean hasRetCode() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional .com.msgtouch.common.proto.RetCode retCode = 14;</code>
       */
      public com.msgtouch.network.socket.packet.MsgPBPacket.RetCode getRetCode() {
        com.msgtouch.network.socket.packet.MsgPBPacket.RetCode result = com.msgtouch.network.socket.packet.MsgPBPacket.RetCode.valueOf(retCode_);
        return result == null ? com.msgtouch.network.socket.packet.MsgPBPacket.RetCode.TIMEOUT : result;
      }
      /**
       * <code>optional .com.msgtouch.common.proto.RetCode retCode = 14;</code>
       */
      public Builder setRetCode(com.msgtouch.network.socket.packet.MsgPBPacket.RetCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00002000;
        retCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.msgtouch.common.proto.RetCode retCode = 14;</code>
       */
      public Builder clearRetCode() {
        bitField0_ = (bitField0_ & ~0x00002000);
        retCode_ = 1000;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.msgtouch.common.proto.Packet)
    }

    // @@protoc_insertion_point(class_scope:com.msgtouch.common.proto.Packet)
    private static final com.msgtouch.network.socket.packet.MsgPBPacket.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.msgtouch.network.socket.packet.MsgPBPacket.Packet();
    }

    public static com.msgtouch.network.socket.packet.MsgPBPacket.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    public com.msgtouch.network.socket.packet.MsgPBPacket.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_msgtouch_common_proto_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_msgtouch_common_proto_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026proto/msg_packet.proto\022\031com.msgtouch.c" +
      "ommon.proto\"\327\002\n\006Packet\0223\n\007msgType\030\001 \001(\0162" +
      "\".com.msgtouch.common.proto.MsgType\022\013\n\003s" +
      "eq\030\002 \001(\t\022\017\n\007appName\030\003 \001(\t\0228\n\010platform\030\004 " +
      "\001(\0162&.com.msgtouch.common.proto.AppPlatf" +
      "orm\022\013\n\003cmd\030\005 \001(\t\022\022\n\ncustomerId\030\006 \001(\t\022\013\n\003" +
      "uid\030\007 \001(\004\022\r\n\005error\030\010 \001(\t\022\r\n\005eBody\030\t \001(\014\022" +
      "\016\n\006gameId\030\n \001(\t\022\r\n\005advno\030\013 \001(\t\022\022\n\nsdkVer" +
      "sion\030\014 \001(\t\022\014\n\004imei\030\r \001(\t\0223\n\007retCode\030\016 \001(" +
      "\0162\".com.msgtouch.common.proto.RetCode*,\n",
      "\013AppPlatform\022\013\n\007Android\020\001\022\007\n\003Web\020\002\022\007\n\003Io" +
      "s\020\003*$\n\007MsgType\022\013\n\007Request\020\001\022\014\n\010Response\020" +
      "\002*\203\001\n\007RetCode\022\014\n\007TIMEOUT\020\350\007\022\006\n\002OK\020\000\022\026\n\tE" +
      "XCEPTION\020\377\377\377\377\377\377\377\377\377\001\022\030\n\013PROTO_ERROR\020\376\377\377\377\377" +
      "\377\377\377\377\001\022\035\n\020ERROR_NO_SESSION\020\375\377\377\377\377\377\377\377\377\001\022\021\n\004" +
      "PUSH\020\374\377\377\377\377\377\377\377\377\001B1\n\"com.msgtouch.network." +
      "socket.packetB\013MsgPBPacket"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_msgtouch_common_proto_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_msgtouch_common_proto_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_msgtouch_common_proto_Packet_descriptor,
        new java.lang.String[] { "MsgType", "Seq", "AppName", "Platform", "Cmd", "CustomerId", "Uid", "Error", "EBody", "GameId", "Advno", "SdkVersion", "Imei", "RetCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
